Changed Fonts and Minor changes in Footer
devlup-labs/gymkhana-inventory pull request #37
Opened 2021-03-01 12:12 UTC by suyashagno3

1. Changed Fonts as decided
2. Minor changes in Footer as mentioned in design
![fonts1](https://user-images.githubusercontent.com/56470855/109495596-80974a80-7ab5-11eb-995d-8947fd01b466.png)

2021-03-03 16:49 UTC, Anshultilondiya requested changes

2021-03-03 16:49 UTC, Anshultilondiya commented on frontend/src/App.css
> +@media screen and (max-width: 600px) {
Use Material-Ui Grid or Form for making it responsive

2021-03-05 16:53 UTC, Anshultilondiya commented
@suyashagno3 could you please resolve conflicts in App.css

2021-03-05 17:00 UTC, suyashagno3 commented
@Anshultilondiya  Done

2021-03-05 17:21 UTC, suyashagno3 commented
@Anshultilondiya Fixed it...

2021-03-06 07:51 UTC, merged